package copilotclient

// Github API reference https://docs.github.com/en/rest/copilot/copilot-usage?apiVersion=2022-11-28
// Autogenerated struct by the JSON-to-Go utility

type CopilotMetricsBody struct {
	Day                   string `json:"day"`
	TotalSuggestionsCount int    `json:"total_suggestions_count"`
	TotalAcceptancesCount int    `json:"total_acceptances_count"`
	TotalLinesSuggested   int    `json:"total_lines_suggested"`
	TotalLinesAccepted    int    `json:"total_lines_accepted"`
	TotalActiveUsers      int    `json:"total_active_users"`
	TotalChatAcceptances  int    `json:"total_chat_acceptances"`
	TotalChatTurns        int    `json:"total_chat_turns"`
	TotalActiveChatUsers  int    `json:"total_active_chat_users"`
	Breakdown             []struct {
		Language         string `json:"language"`
		Editor           string `json:"editor"`
		SuggestionsCount int    `json:"suggestions_count"`
		AcceptancesCount int    `json:"acceptances_count"`
		LinesSuggested   int    `json:"lines_suggested"`
		LinesAccepted    int    `json:"lines_accepted"`
		ActiveUsers      int    `json:"active_users"`
	} `json:"breakdown"`
}
